---

- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create the new database(s)"
      postgresql_db:
        name: "{{ item.db }}"
        port: "{{ db_port | default('5432') }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"
        state: present
      with_items: "{{ databases }}"

    - name: Create user(s)
      postgresql_user:
        login_host: "{{ db_host }}"
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"
        port: "{{ db_port | default('5432') }}"
        db: "{{ item.db }}"
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        role_attr_flags: "SUPERUSER"
      with_items: "{{ databases }}"
